### ISSUE TITLE
Missing source should return 404 not 500

### ISSUE THREAD

**Issue by varontron** [Novartis/YADA#104]
Currently a request to a non-existent data source returns a 500 error to the caller.  Like missing (or typo'd) qnames, the service should return a 404 error.

**Comment by varontron** [comment]
YADA does return a 404 when a non-existent datasource is requested:

```
curl -vi -XGET "http://localhost:8080/yada/q/YADAFOO/test%20SELECT"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /yada/q/YADAFOO/test%20SELECT HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 
HTTP/1.1 404 
< Set-Cookie: JSESSIONID=41F2D5F5E35568E9729CBBDE8AF2B0E1; Path=/; HttpOnly
Set-Cookie: JSESSIONID=41F2D5F5E35568E9729CBBDE8AF2B0E1; Path=/; HttpOnly
< X-YADA-VERSION: 9.0.0-SNAPSHOT
X-YADA-VERSION: 9.0.0-SNAPSHOT
< Content-Type: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Tue, 08 Sep 2020 05:36:39 GMT
Date: Tue, 08 Sep 2020 05:36:39 GMT

< 



{"App":"UNKNOWN","Status":404,"Help":"https://github.com/Novartis/YADA#other","Message":"Failed to load query `YADAFOO/test SELECT`. Check spelling and case in request.","Query":"","StackTrace":["com.novartis.opensource.yada.YADAFinderException: Failed to load query `YADAFOO/test SELECT`. Check spelling and case in request.","at com.novartis.opensource.yada.Finder.getQueryFromLib(Finder.java:658)","at com.novartis.opensource.yada.Finder.getQuery(Finder.java:688)","at com.novartis.opensource.yada.QueryManager.endowQuery(QueryManager.java:1002)","at com.novartis.opensource.yada.QueryManager.processRequest(QueryManager.java:204)","at com.novartis.opensource.yada.QueryManager.<init>(QueryManager.java:149)","at com.novartis.opensource.yada.Service.execute(Service.java:597)","at org.apache.jsp.yada_jsp._jspService(yada_jsp.java:244)","at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)","at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)","at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)","at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)","at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)","at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)","at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)","at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)","at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)","at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)","at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)","at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)","at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)","at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)","at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)","at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)","at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)","at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)","at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)","at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)","at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)","at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)","at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)","at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)","at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)","at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)","at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)","at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1506)","at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)","at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)","at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)","at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)","at java.base/java.lang.Thread.run(Thread.java:832)","Caused by: java.nio.file.NoSuchFileException: /usr/local/YADA/lib/YADAFOO/test SELECT.json","at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)","at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)","at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)","at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)","at java.base/java.nio.file.Files.newByteChannel(Files.java:375)","at java.base/java.nio.file.Files.newByteChannel(Files.java:426)","at java.base/java.nio.file.Files.readAllBytes(Files.java:3272)","at com.novartis.opensource.yada.Finder.getQueryFromLib(Finder.java:652)","... 51 more","Caused by:","java.nio.file.NoSuchFileException: /usr/local/YADA/lib/YADAFOO/test SELECT.json","at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)","at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)","at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)","at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)","at java.base/java.nio.file.Files.newByteChannel(Files.java:375)","at java.base/java.nio.file.Files.newByteChannel(Files.java:426)","at java.base/java.nio.file.Files.readAllBytes(Files.java:3272)","at com.novartis.opensource.yada.Finder.getQueryFromLib(Finder.java:652)","at com.novartis.opensource.yada.Finder.getQuery(Finder.java:688)","at com.novartis.opensource.yada.QueryManager.endowQuery(QueryManager.java:1002)","at com.novartis.opensource.yada.QueryManager.processRequest(QueryManager.java:204)","at com.novartis.opensource.yada.QueryManager.<init>(QueryManager.java:149)","at com.novartis.opensource.yada.Service.execute(Service.java:597)","at org.apache.jsp.yada_jsp._jspService(yada_jsp.java:244)","at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)","at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)","at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)","at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)","at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)","at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)","at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)","at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)","at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)","at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)","at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)","at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)","at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)","at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)","at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)","at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)","at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)","at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)","at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)","at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)","at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)","at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)","at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)","at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)","at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)","at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)","at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)","at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)","at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)","at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)","at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1506)","at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)","at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)","at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)","at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)","at java.base/java.lang.Thread.run(Thread.java:832)"],"StatusText":"Not Found","Params":[],"Source":"https://github.com/Novartis/YADA","Exception":"com.novartis.opensource.yada.YADAFinderException","Type":"GET","Qname":"UNKNOWN","Version":"9.0.0-SNAPSHOT","Links":["https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Finder.java#L658","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Finder.java#L688","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L1002","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L204","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L149","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Service.java#L597","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Finder.java#L652","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Finder.java#L652","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Finder.java#L688","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L1002","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L204","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/QueryManager.java#L149","https://github.com/Novartis/YADA/blob/master/yada-api/src/main/java/com/novartis/opensource/yada/Service.java#L597"]}

* Connection #0 to host localhost left intact
* Closing connection 0

```
