### ISSUE TITLE
Improve default yada.jsp output

### ISSUE THREAD

**Issue by alokito** [Novartis/YADA#7]
yada.jsp with no arguments currently returns a 500 null pointer exception.
It would be better if it spat out a link to some documentation, perhaps with a list of the available queries.

**Comment by varontron** [comment]
Most exceptions that bubble up to the Service object are encapsulated in a JSON string sent back to the requester.  There was a use-case which you encountered where the `Service.error()` method itself threw a null-pointer.  This has been resolved.  The result of an 'empty YADA request', e.g., `http://localhost:8081/yada.jsp` now, like other exceptions will resemble the following.  On your suggestion, I've added the `Source` and `Help` keys, pointing to the appropriate URLs, to the JSON: 
```json
{
"Qname": "UNKNOWN",
"Source": "https://github.com/Novartis/YADA",
"Exception": "com.novartis.opensource.yada.YADARequestException",
"Help": "http://opensource.nibr.com/projects/YADA/#other",
"Message": "Your request must contain a 'qname', 'q', 'JSONParams', or 'j' parameter.",
"Type": "GET",
"Query": "",
"Params": [],
"StackTrace": [
"com.novartis.opensource.yada.YADARequestException: Your request must contain a 'qname', 'q', 'JSONParams', or 'j' parameter.",
"at com.novartis.opensource.yada.QueryManager.processQueries(QueryManager.java:199)",
"at com.novartis.opensource.yada.QueryManager.<init>(QueryManager.java:156)",
"at com.novartis.opensource.yada.Service.execute(Service.java:568)",
"at org.apache.jsp.yada_jsp._jspService(yada_jsp.java:115)",
"at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)",
"at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)",
"at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)",
"at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)",
"at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)",
"at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)",
"at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)",
"at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)",
"at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)",
"at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)",
"at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)",
"at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:205)",
"at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:266)",
"at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)",
"at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)",
"at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)",
"at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)",
"at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)",
"at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)",
"at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)",
"at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)",
"at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)",
"at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)",
"at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)",
"at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)",
"at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)",
"at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)",
"at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)",
"at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)",
"at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)",
"at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)",
"at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)",
"at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
"at java.lang.Thread.run(Thread.java:745)"
]
}
```

**Comment by varontron** [comment]
Last commit [306088e](https://github.com/Novartis/YADA/commit/306088edf089fee6de1aa54064127e5d57eada2a) improves upon this further by mapping HTTP status codes to various errors. Undocumented currently, and will be part of release 6.3, but see [yada.jsp](https://github.com/Novartis/YADA/commit/306088edf089fee6de1aa54064127e5d57eada2a#diff-6967ce738d702b647e8b50b0b5056be5) for details
